[package]
name                 = "dive-abi"
description          = "Google Tensor SDK v2 RISC-V Dive runtime ABI and status type"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
keywords.workspace   = true
categories.workspace = true

[dependencies]

[lints]
workspace = true
